#!/usr/bin/env ruby
# encoding: utf-8
cmd = "nmap"
addr = "192.168.122.131"
user = "interact"
passwrd = "963741"
require 'net/ssh'
arguments = ""
argnum = 0
storedir = "/home/haden/kali-stored"


time = Time.now
for arg in ARGV
  argnum = argnum + 1
  arguments = arguments + " " + arg.to_s
end
puts argnum
fullcmd = cmd + arguments 
puts "-"*20 + "Start time : " + time.inspect + "-"*20
Net::SSH.start(addr, user, :password => passwrd) do |ssh|
  output = ssh.exec!(fullcmd)
  puts output

  log = File.open(storedir + "/" + cmd,"w")
  log.write(output)
  

end
