#!/usr/bin/python3
import paramiko
import time
try: 
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    time.sleep(1)
    ssh.connect("192.168.122.131", username="root", password="meis=@livetod@y")
    ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command("ifconfig > ifconfig.txt")
except:
    pass



